### ISSUE TITLE
"%1 is not a valid win32 application" error

### ISSUE THREAD

**Issue by PiggyWhiskey** [nneonneo/2048-ai#39]
I heard of this AI and managed to build it and installed python (never worked with it before)

But when I run the 2048.py file I'm getting a weird error.

Traceback (most recent call last):
  File "2048.py", line 18, in <module>
    ailib = ctypes.CDLL(dllfn)
  File "E:\Program Files\Python\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

Any advice?

**Comment by PiggyWhiskey** [comment]
Re-built with the 32bit VS command line and it work. :/
