### ISSUE TITLE
some problem about 2048-ai

### ISSUE THREAD

**Issue by halfrost** [nneonneo/2048-ai#50]
I’m interesting in your 2048-ai in github. But i can’t run it with some problem:

I execute :

./configure
make
sudo /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chre –remote-debugging-port=9222
python /Users/YDZ/Downloads/2048-ai-master/2048.py -b chrome

but after these command,some problems have arisen:

Traceback (most recent call last):
 File "/Users/YDZ/Downloads/2048-ai-master/2048.py", line 149, in <module>
   exit(main(sys.argv[1:]))
 File "/Users/YDZ/Downloads/2048-ai-master/2048.py", line 130, in main
   ctrl = ChromeDebuggerControl(args.port)
 File "/Users/YDZ/Downloads/2048-ai-master/chromectrl.py", line 18, in __init__
   pages = json.loads(urllib2.urlopen('http://localhost:%d/json/list' % port).read())
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
   return opener.open(url, data, timeout)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
   response = meth(req, response)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
   'http', request, response, code, msg, hdrs)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
   return self._call_chain(*args)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
   result = func(*args)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
   raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

I puzzled what is the problem ? Could you help me ? Thanks!

**Comment by nneonneo** [comment]
That's odd - `/json/list` should not throw a 503 error.

Try the following:

- Use a different port than 9222 (use the `-p` option to `2048.py` to set the port)
- Don't start Chrome with sudo

I tried the AI just now with Chrome 63, macOS 10.12.6, and it worked fine.

**Comment by halfrost** [comment]
Let me show you my steps, can you help me to see if the following is correct?

1. In terminal

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome –remote-debugging-port=9553

```

2. Chrome will open , I enter 2048 web page.

![](https://user-images.githubusercontent.com/10825609/34079177-0fbdb962-e363-11e7-845c-a2e037917791.png)

3. This is terminal log . These are some error. Do they matter?(
I use the blue rectangular line drawn in the picture)



<img width="1158" alt="_2017-12-17_ 7_36_157" src="https://user-images.githubusercontent.com/10825609/34079195-901afa7a-e363-11e7-86fd-641037bce0fa.png">


4. Then in terminal

```

python 2048.py -b chrome -p 9553

```

<img width="913" alt="2017-12-17 7 39 47" src="https://user-images.githubusercontent.com/10825609/34079201-c1bde6be-e363-11e7-8659-53824c6b34db.png">

The same 503 error.


-----------------------------------------------------------

macOS High Sierra 10.13.2 (17C88) Chrome 63.0.3239.108 ,  I think there should be no great relationship between these versions. 


The above steps are correct? Where else is there any problem?

**Comment by nneonneo** [comment]
I think it should be `--remote-debugging-port`, with two dashes. Try that.

Here's what I get in my Terminal when I do that:

```
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222

DevTools listening on ws://127.0.0.1:9222/devtools/browser/c45f9b3b-c4de-4348-8f0b-302f3ae960b5
```
