### ISSUE TITLE
chrome on linux error!?

### ISSUE THREAD

**Issue by Zibri** [nneonneo/2048-ai#56]
Selection? 1
Traceback (most recent call last):
  File "./2048.py", line 149, in <module>
    exit(main(sys.argv[1:]))
  File "./2048.py", line 130, in main
    ctrl = ChromeDebuggerControl(args.port)
  File "/home/zibri/2048-ai/chromectrl.py", line 37, in __init__
    self.ws = websocket.create_connection(wsurl)
AttributeError: 'module' object has no attribute 'create_connection'

**Comment by Zibri** [comment]
Since uninstalling websocket and then installing websocket-client didn't work,
I solved by doing:
```
$ sudo rm -rf /usr/local/lib/python*/dist-packages/websocket
$ sudo pip2 install websocket-client
```
And it worked after killing all chrome sessions (sudo killall chrome)
and restarting chrome with
`$ google-chrome --remote-debugging-port=9222
`
