### ISSUE TITLE
[WinError 193] %1 is not a valid win32 application

### ISSUE THREAD

**Issue by DarkerMinecraft** [nneonneo/2048-ai#79]
I have run through your build process for Visual Studios and I run into this problem. 

Traceback (most recent call last):
  File "C:\Users\nayon\OneDrive\Desktop\2048-ai\2048.py", line 9, in <module>
    from ailib import ailib, to_c_board, from_c_index
  File "C:\Users\nayon\OneDrive\Desktop\2048-ai\ailib.py", line 8, in <module>
    ailib = ctypes.CDLL(dllfn)
  File "C:\Users\nayon\.pyenv\pyenv-win\versions\3.13.0\Lib\ctypes\__init__.py", line 390, in __init__
    self._handle = _dlopen(self._name, mode)
                   ~~~~~~~^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by nneonneo** [comment]
You might be trying to use a 32-bit DLL with 64-bit Python or vice-versa. See this post for more details: https://stackoverflow.com/questions/19849077/error-loading-dll-in-python-not-a-valid-win32-application

**Comment by nneonneo** [comment]
Windows does not unfortunately support "fat" binaries which have both architectures. Your best bet is to build it twice: build once using the x86 tools, rename/move the resulting files, and then build again using the x64 tools.
